apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperledger-peer1
  labels:
    app: hyperledger
    role: peer1
spec:
  replicas: 1
  template:
    metadata:
      name: hyperledger-peer-container
      labels:
        role: peer1
    spec:
      restartPolicy: Always
      containers:
        - name: peer-container1
          imagePullPolicy: Never
          image: hyperledger/fabric-peer:latest
          env:
            - name: CORE_PEER_ID
              value: vp1
            - name: CORE_PEER_DISCOVERY_ROOTNODE
              value: "vp0:7051"
            - name: CORE_SECURITY_ENROLLID
              value: "test_vp1"
            - name: CORE_SECURITY_ENROLLSECRET
              value: "5wgHK9qqYaPy"
            - name: CORE_PEER_PKI_ECA_PADDR
              value: "member-service:7054"
            - name: CORE_PEER_PKI_TCA_PADDR
              value: "member-service:7054"
            - name: CORE_PEER_PKI_TLSCA_PADDR
              value: "member-service:7054"
          args:
            - sh
            - -c
            - "sleep 10; peer node start"
            # - peer
            # - node
            # - start
